[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyRPCFPost"
version = "0.0.1"
dependencies = ["numpy",
                "scipy",
                "matplotlib",
                "h5py",
                "configParser"]
